# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12P1DCeiGbWXpk9tX4d8fnbou_1JajwEN
"""

import json
import os
import re
import time
from datetime import datetime

import requests


BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}
MAX_IDS = 500
MAX_PER_CATEGORY = 25


CATEGORIES = {
    "technology": ["AI", "software", "tech", "code", "computer", "data",
                   "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election",
                  "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player",
               "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology",
                "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book",
                      "show", "award", "streaming"],
}


def matches(title, keywords):
    """Return True if any keyword appears in the title (case-insensitive, whole word)."""
    for kw in keywords:
        if re.search(r"\b" + re.escape(kw) + r"\b", title, re.IGNORECASE):
            return True
    return False


def get_json(url):
    """GET a URL and return parsed JSON, or None if the request fails."""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=10)
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        print(f"Request failed for {url}: {e}")
        return None


def main():

    ids = get_json(f"{BASE_URL}/topstories.json")
    if not ids:
        print("Could not fetch top story IDs. Exiting.")
        return
    ids = ids[:MAX_IDS]
    print(f"Fetched {len(ids)} story IDs. Fetching story details...")


    stories = []
    for story_id in ids:
        item = get_json(f"{BASE_URL}/item/{story_id}.json")
        if item and item.get("title"):   # skip failed / title-less items
            stories.append(item)
    print(f"Retrieved details for {len(stories)} stories.")


    collected = []
    used_ids = set()
    for category, keywords in CATEGORIES.items():
        count = 0
        for item in stories:
            if count >= MAX_PER_CATEGORY:
                break
            if item["id"] in used_ids or not matches(item["title"], keywords):
                continue
            collected.append({
                "post_id": item.get("id"),
                "title": item.get("title"),
                "category": category,
                "score": item.get("score"),
                "num_comments": item.get("descendants", 0),
                "author": item.get("by"),
                "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            })
            used_ids.add(item["id"])
            count += 1
        print(f"  {category}: {count} stories")
        time.sleep(2)   # one 2-second pause per category


    os.makedirs("data", exist_ok=True)
    filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(collected, f, indent=2, ensure_ascii=False)

    print(f"Collected {len(collected)} stories. Saved to {filename}")


if __name__ == "__main__":
    main()

import glob
import os

import pandas as pd


files = sorted(glob.glob("data/trends_*.json"))
if not files:
    raise SystemExit("No data/trends_*.json found. Run task1_data_collection.py first.")
json_file = files[-1]

df = pd.read_json(json_file)
print(f"Loaded {len(df)} stories from {json_file}\n")


df = df.drop_duplicates(subset="post_id")
print(f"After removing duplicates: {len(df)}")


df = df.dropna(subset=["post_id", "title", "score"])
print(f"After removing nulls: {len(df)}")


df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].fillna(0).astype(int)


df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")


df["title"] = df["title"].str.strip().str.replace(r"\s+", " ", regex=True)


os.makedirs("data", exist_ok=True)
df.to_csv("data/trends_clean.csv", index=False)
print(f"\nSaved {len(df)} rows to data/trends_clean.csv")


print("\nStories per category:")
for category, count in df["category"].value_counts().items():
    print(f"  {category:<15}{count}")

import numpy as np
import pandas as pd


df = pd.read_csv("data/trends_clean.csv")
print(f"Loaded data: {df.shape}\n")
print("First 5 rows:")
print(df.head(), "\n")
print(f"Average score   : {df['score'].mean():,.0f}")
print(f"Average comments: {df['num_comments'].mean():,.0f}\n")


scores = df["score"].to_numpy()
print("--- NumPy Stats ---")
print(f"Mean score   : {np.mean(scores):,.0f}")
print(f"Median score : {np.median(scores):,.0f}")
print(f"Std deviation: {np.std(scores):,.0f}")
print(f"Max score    : {np.max(scores):,}")
print(f"Min score    : {np.min(scores):,}\n")


counts = df["category"].value_counts()
print(f"Most stories in: {counts.idxmax()} ({counts.max()} stories)\n")


top = df.iloc[np.argmax(df["num_comments"].to_numpy())]
print(f"Most commented story: \"{top['title']}\"  - {top['num_comments']:,} comments\n")


df["engagement"] = df["num_comments"] / (df["score"] + 1)
df["is_popular"] = df["score"] > df["score"].mean()


df.to_csv("data/trends_analysed.csv", index=False)
print("Saved to data/trends_analysed.csv")